"""empty message

Revision ID: c3ccc721f4c3
Revises: dfc9f8c0256b
Create Date: 2019-12-05 10:36:53.761671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3ccc721f4c3'
down_revision = 'dfc9f8c0256b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_role', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='角色名称',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_role', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=False)
    # ### end Alembic commands ###
